-- Drop all procedures
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_PURCHASE_FLATTEN;
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_INVOICE_VALIDATED;
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_PURCHASE_VALIDATED;
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MOVEFILES_TO_SOURCE;
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.IGNOREFILES_TO_STAGE;

-- Drop all tasks
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.EXTRACT_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.FLATTEN_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.VALIDATE_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.PREPROCESSING;

-- Drop any additional objects referenced in the script
-- Note: Ensure these objects exist before attempting to drop them
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.SCORE_THRESHOLD;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MODEL_METADATA;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Purchase_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Invoice_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Purchase_Validated;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Invoice_Validated;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.DocAI_OrderForm_Extraction;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.purchase_col_score_failed_history;

-- Additional cleanup for stages if needed
REMOVE @manual_review;
REMOVE @INVOICE_DOCS;
REMOVE @IGNORED_DOCS;
