-- Drop all procedures
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.COUNT_PDF_PAGES_PROC();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.HANDLE_PDF_FILES();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MANAGE_MANUAL_REVIEW_FILES();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_MODEL_FLATTEN();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_MODEL_VALIDATED();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MOVEFILES_TO_SOURCE(VARCHAR);
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.IGNOREFILES_TO_STAGE(VARCHAR);

-- Drop all tasks
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.EXTRACT_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.FLATTEN_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.VALIDATE_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.PREPROCESSING;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MANUAL_CHECKUP_FILES;

-- Drop any additional objects referenced in the script
-- Note: Ensure these objects exist before attempting to drop them
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MODEL_METADATA;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.SCORE_THRESHOLD;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.INVOICE_COL_SCORE_FAILED_HISTORY;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.PURCHASE_COL_SCORE_FAILED_HISTORY;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MANUAL_REVIEW_HISTORY_LOG;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.DOCAI_PREFILTER;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.DOCAI_ORDERFORM_EXTRACTION;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Invoice_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Purchase_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Invoice_Validated;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Purchase_Validated;

-- Additional cleanup for stages if needed
REMOVE @MANUAL_REVIEW;
REMOVE @INVOICE_DOCS;
REMOVE @IGNOIRED_DOCS;